# Default values for demo-java-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environnement: ovh
phase: dev

image:
  repository: harbor.apps.c6.numerique-interieur.com/mi-certifdamjanlab1/
  name: java-demo
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "master"

imagePullSecrets:
  - name: "registry-pull-secret"
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8080

ingress:
  enabled: true
  secret:
    enabled: true
  host: damjan-certif.dev.numerique-interieur.com

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "512Mi"
    cpu: "500m"

global:
  postgresql:
    auth:
      existingSecret: my-secret
      secretKeys:
        userPasswordKey: "PG_PASSWORD"
        adminPasswordKey: "PG_PASSWORD"
      username: "userdemo"
      database: "demodb"

# Contrainte de sécurité Openshift
postgresql:
  fullnameOverride: postgres-demo
  volumePermissions:
    enabled: false
    securityContext:
      runAsUser: "auto"
  securityContext:
    enabled: false
  shmVolume:
    chmod:
      enabled: false
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  primary:
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "512Mi"
        cpu: "500m"
    volumePermissions:
      enabled: false
      securityContext:
        runAsUser: "auto"
    securityContext:
      enabled: false
    shmVolume:
      chmod:
        enabled: false
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
