apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-java-helm.fullname" . }}
  labels:
    {{- include "demo-java-helm.labels" . | nindent 4 }}
    app: dso-demo-java
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-java-helm.selectorLabels" . | nindent 6 }}
      app: dso-demo-java
  template:
    metadata:
      labels:
        {{- include "demo-java-helm.selectorLabels" . | nindent 8 }}
        app: dso-demo-java
    spec:
      serviceAccountName: tuto-sa
      serviceAccount: tuto-sa
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: PG_PASSWORD
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.global.postgresql.auth.username }}
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Values.postgresql.fullnameOverride }}:5432/{{ .Values.global.postgresql.auth.database }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
